### ISSUE TITLE
Ensure good nginx/rtmp access controls

### ISSUE THREAD

**Issue by GoogleBot42** [ptdel/tswf#22]
Make sure that all nginx configuration files have "deny" directives where applicable.

**Comment by ptdel** [comment]
https://github.com/ptdel/tswf/blob/5edfbc02af5009ee846592fee0390303dc9acb50/rtmp.conf#L8-L11
would we add one after the `allow publish 127.0.0.1`, something like `deny publish all`?

**Comment by GoogleBot42** [comment]
@ptdel  yep. that's how we'd fix it.
